### ISSUE TITLE
Not an issue, just appreciation

### ISSUE THREAD

**Issue by x4080** [Mr-Pine/Zoomables#10]
Hi, I think what you create is very good. Thanks a lot

To other that needed some sample how to use it, here it is :
```
val scope = rememberCoroutineScope()
val zoomableState = rememberZoomableState()

...
ZoomableImage(
		modifier = Modifier
			.fillMaxWidth()
			.fillMaxHeight(0.95f),
		coroutineScope = scope, zoomableState = zoomableState,		
	)	
```

**Comment by Mr-Pine** [comment]
Hey, thanks for the compliment, happy to help.

Can I use that Sample in the readme? You are also very welcome to make a PR if you'd like to get the credit ;)

**Comment by x4080** [comment]
Sure, thats what I got some trouble at first since there's no example yet, hopefully it will help all your component user

**Comment by Mr-Pine** [comment]
Thanks for your suggestion, I'll close this issue now
