### ISSUE TITLE
[Feature request] Allow some additional configuration

### ISSUE THREAD

**Issue by ammargitham** [Mr-Pine/Zoomables#15]
It would be great if you can also add the following to `ZoomableImage`:
1. An `onTap` callback. If I add my own pointerInput to the modifier to detect single taps, it breaks the double tap zoom.
2. Currently the default double tap only zooms it to 2f scale. Allow us to change this value. I know I could just copy the double tap implementation and give my own value, but I think it would be better if the double tap zoom value is configurable.
3. Also, allow changing the double tap AnimationSpec. This way we can give our own animation easing, duration etc.

**Comment by Mr-Pine** [comment]
Do you have an API in mind for 2 and 3? Maybe a generator function?

**Comment by ammargitham** [comment]
Well, maybe you can add a `doubleTapBehaviour` parameter to `rememberZoomableState` which would can take a `DoubleTapBehaviour` class object.

```kotlin
class DoubleTapBehaviour {
    onDoubleTap: (Offset) -> Unit = <default implementation>,
    minScale: Float = 1f,
    maxScale: Float = 2f,
    animationSpec: AnimationSpec<Float> = <default animation spec>,
}
```

**Comment by ammargitham** [comment]
Honestly, I just want a way to set the double zoom scale value and the animation spec. I just suggested one way from the top of my head. I added `minScale` just as an example. I don't really need it.

**Comment by Mr-Pine** [comment]
All possible in 1.3.0

**Comment by ammargitham** [comment]
Thanks! It works. Although we now have to provide the `coroutineScope` in both `ZoomableImage` and `DefaultDoubleTapBehaviour` if we are overriding it. Maybe later you can re-think the api to simplify it but for now it works. Thank you.
