### ISSUE TITLE
Single touch pan does not trigger onTransformation

### ISSUE THREAD

**Issue by ammargitham** [Mr-Pine/Zoomables#17]
As the title says, single touch panning does not call the `onTransformation` function of `rememberZoomableState`. It is triggered for multi-touch. Just to add, `dragGestureMode` was set to `{ DragGestureMode.PAN }`.

Was trying to debug the issue, I think this line is the cause:
https://github.com/Mr-Pine/Zoomables/blob/b09cc452c3c1eb2741e75a56ee087d19744add7c/zoomables/src/main/kotlin/de/mr_pine/zoomables/Zoomables.kt#L216

**Comment by Mr-Pine** [comment]
Yup, that should probably call `zoomableState.transformBy`. As I'm currently not at home, I probably won't get to fix it until end of next week though :(

**Comment by ammargitham** [comment]
Hey, did you have any time to work on this?

**Comment by Mr-Pine** [comment]
Yup, it's mostly fixed now, should get to release it in the next couple of days, hopefully tomorrow

**Comment by Mr-Pine** [comment]
Is adressed with 1.4.0
