### ISSUE TITLE
[Zoomable] Add feature to disable swipeability in zoomed state

### ISSUE THREAD

**Issue by ajans** [Mr-Pine/Zoomables#5]
Hi,

thanks again you for your library!

As I understand the parameters `minimumSwipeDistance` and `onSwipeLeft` / `onSwipeRight`, those parameters are designed to handle something like a Pager-like scenario in the unzoomed state, right?

In my app, I already tested your `Zoomable` in the context of the `HorizontalPager`-composable from the accompanist-library `"com.google.accompanist:accompanist-pager:0.23.1"`, so my use-case is a bit different, as page-swiping is already handled by `HorizontalPager`.

The problem for me with the usage of `Zoomable` in `HorizontalPager` is the gesture-conflict happening in the zoomed state.
Depending on how slow or fast I do the drag-gesture, either `Zoomable` is panning the viewport to the zoomed content or `HorizontalPager` picks up the gesture and starts to swipe to the next page, which is not what the app-user would expect.

For me, the best solution would be to disable page-swiping if the `Zoomable` is in the zoomed state.
Would that be something that could be handled by `Zoomable` on its own or would I need to adapt the `HorizontalPager` for that somehow in regards to gesture-propagation?

I found [this issue](https://github.com/google/accompanist/issues/1018) for disabling swipe for `HorizontalPager`, but the parameter for that is only re-introduced in a newer version of accompanist than I am currently using (it also depends on the newer alpha-version of Jetpack Compose).
So I guess the alternative for me would be to migrate to the newer accompanist-version and handle this by bubbling-up the zoomableState and disable the HorizontalPager-swipe in the zoomed state myself.

What do you think?

**Comment by Mr-Pine** [comment]
I'll see what I can do about how this library captures gestures.

How is it working for you if it's not zoomed in? Does it conflict with the Pager?

**Comment by ajans** [comment]
If it's not zoomed in, there is no conflict since the use-case of panning around the zoomed image does not exist for that case.

**Comment by ajans** [comment]
I think this is not a bug in your library, more a discussion of approach, since the `HorziontalPager` may very well be solely responsible for gesture-interruption here (I don't know, I don't have much experience with low-level gesture detection, especially in Compose).

I will try my proposed solution and let you know if it helps.

**Comment by ajans** [comment]
It works quite good:


                val zoomableState = rememberZoomableState(
                    rotationBehavior = ZoomableState.Rotation.DISABLED,
                )

                HorizontalPager(
                    modifier = Modifier.weight(weight = 0.9f),
                    count = galleryItems!!.size,
                    state = pagerState,
                    key = { page -> galleryItems!![page].id },
                    userScrollEnabled = zoomableState.scale.value in 0.92f..1.08f,
                ) { page ->
                    val galleryItem = galleryItems!![page]
                    when (galleryItem.itemType) {
                        ITEMTYPE_GALLERY_IMAGE -> {
                            ImagePage(
                                imageItem = galleryItem,
                                zoomableState = zoomableState,
                            )
                        }

I think the only problem is, sometimes the `minimumSwipeDistance`-related logic in `Zoomable` might still interfere with registering a page-swipe as you can see in the recording. I tried to disable this logic by setting `minimumSwipeDistance` to `Int.MAX_VALUE`, it helps a little but not much. This does not happen on a video-page as those are not using `Zoomable`.

Recording:

https://user-images.githubusercontent.com/3482744/161762063-8388a901-e94d-4ec2-b7e7-4051dcc9ba64.mp4

**Comment by Mr-Pine** [comment]
I wrote the gesture code quite a while ago so I'm not totally sure how it works exactly anymore, but I think disabling all drag gestures when not zoomed in would fix your problem.

I think this would be achieved by putting an if clause around all the dragging code (ll. 201-240 in your fork / 201-238 in my code)

**Comment by ajans** [comment]
I tested this with https://github.com/ajans/Zoomables/commit/7beddb70d27fd2316c45d2ff776ce8bd67344cee and it works great!
Would that be a change you would accept for a merge request or does that conflict with some other use-case you had in mind?

**Comment by ajans** [comment]
Of course, minimumSwipeDistance and onSwipeLeft/onSwipeRight would not have to be optional anymore, as this change did not really help with the swipe-conflict.

I would cherry-pick your proposed solution into a new branch and do a merge-request with that if it is okay for you?

**Comment by Mr-Pine** [comment]
I'd be happy to accept a PR!

I think it would be a good idea to add a boolean parameter to enable/disable swiping gestures to add versatility

**Comment by ajans** [comment]
I created a PR here: https://github.com/Mr-Pine/Zoomables/pull/8

**Comment by Mr-Pine** [comment]
This should work in 1.1.2 by passing `dragGesturesEnabled = {!notTransformed}` to the Zoomable

**Comment by ajans** [comment]
Thank you very much! I will test this and let you know!

**Comment by ajans** [comment]
It works great!

At the start I had the issue of it behaving like before with the page-swipe conflict, but I think I just had a build-cache issue. I cleaned and rebuilt everything and that fixed it.

**Comment by Mr-Pine** [comment]
Glad I could help! If you have any more issues/suggestions feel free to tell me :)
